name: Проверка репозитория
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест на проверку кол-во человек
      run: |
        chmod +x test1.sh
        ./test1.sh
    - name: Тест на однофамильцев
      run: |
        chmod +x test2.sh
        ./test2.sh
